[build]
#   base = "client"
  publish = "build"
  command = "yarn build"

# The following redirect is intended for use with most SPAs that handle routing internally.
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = false
# [build]
#     # command = "npm run build"
#     # base = "./"
#     publish = "./build"

# # The following redirect is intended for use with most SPAs that handle
# # routing internally.
# [[redirects]]
#   from = "/*"
#   to = "/index.html"
#   status = 200
#   force = true
# #   query = {path = ":path"} # apply this rule for /?path=example
# #   headers = {X-From = "Netlify"}

# # Redirect for api:
# [[redirects]]
#   from = "/api/*"
#   to = "https://api.example.com/:splat"
#   status = 200
#   force = true